# Generated by Django 5.0.1 on 2024-02-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='media/DestinationImages')),
            ],
        ),
        migrations.CreateModel(
            name='GuideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=50)),
                ('expirence', models.CharField(max_length=50)),
                ('person_photo', models.ImageField(upload_to='media/GuidePhoto')),
                ('nid_frontside_img', models.ImageField(upload_to='media/NIDImages')),
                ('nid_backside_img', models.ImageField(upload_to='media/NIDImages')),
                ('destination', models.ManyToManyField(related_name='tours', to='tour_package.destinationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('starting_time_date', models.DateTimeField()),
                ('ending_time_date', models.DateTimeField()),
                ('total_seat', models.PositiveSmallIntegerField()),
                ('seat_booking_number', models.PositiveSmallIntegerField()),
                ('bus_start', models.TimeField()),
                ('tour_field', models.CharField(choices=[('Hajj', 'Hajj tour'), ('Couple', 'Couple tour'), ('Institute', 'Institute tour'), ('Business', 'Business tour')], max_length=10)),
                ('per_person_price', models.PositiveIntegerField()),
                ('thumbnail_img', models.ImageField(upload_to='media/ThumbnailImages')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour_package.guidemodel')),
            ],
        ),
    ]
